### ISSUE TITLE
Show tooltip of element on hover

### ISSUE THREAD

**Issue by tkw1536** [KWARC/KAT#17]
We should use the <template> element of the KAnnSpec for this. We also might have to change the templating.

**Comment by LiftnLearn** [comment]
what am i supposed with the non-text data fields, e.g. ranges?

**Comment by tkw1536** [comment]
You should just use the <template> element in the KAnnSpec. 

You can leave out references, they are dealt with in issue #18. 
For selects, just print the <value&gt; of the seleced annotation for now. 

If you are talking about repetitions of fields, we still need to figure out how to deal with that (we will change the template somehow).
