### ISSUE TITLE
Implement repetition of fields

### ISSUE THREAD

**Issue by tkw1536** [KWARC/KAT#23]
- [x] Implement GUI (@LiftnLearn)
  - [x] Text Fields
  - [x] References
  - [x] Selects
- [x] Implement Storing / Loading / Validation (@tkw1536)
    - [x] Text Fields
    - [x] References
    - [x] Selects

**Comment by LiftnLearn** [comment]
The KannSpec we have effectively only has reputations of references, so is it OK if the button appears only for references?

**Comment by tkw1536** [comment]
As I understand it, all fields can have a repetition attached to them with something like \<number atleast="1" atmost="2" />. In the current KAnnSpec it might be the case that only references are actually repeated, but that might change.

**Comment by LiftnLearn** [comment]
Do I have to implement the storing and retrieving of old values as well?

**Comment by tkw1536** [comment]
That is the easier part. Once the GUI for editing is implemented, we can
worry about that.

**Comment by tkw1536** [comment]
@LiftnLearn I saw your code and am implementing storing / loading and validation right now.

**Comment by tkw1536** [comment]
I have finished implementing storing/loading and validation. 

I have done some basic testing and am quite sure I have covered most corner cases. 

@kohlhase @LiftnLearn It would be great if we could do some more testing of this with different KAnnSpec "atleast" and "atmost" values.

**Comment by LiftnLearn** [comment]
Something seems to be wrong with the 'Declaration'; there are no remove buttons and the atmost is ignored.

**Comment by tkw1536** [comment]
@LiftnLearn Fixed, I forgot to update some code for \<select>s.
