### ISSUE TITLE
Fix sidebar open/close

### ISSUE THREAD

**Issue by LiftnLearn** [KWARC/KAT#24]
When you want to open/close the sidebar by hovering over the bar and have an edit/create-field open, then the wrapper seems to block the sidebar where the field is on a vertical level.

**Comment by tkw1536** [comment]
@sourabhlal Can you take a look at this?

**Comment by sourabhlal** [comment]
Ok, I'll check it out tomorrow. To clarify - the issue is that the sidebar doesn't open/close if you hover on what exactly?

**Comment by tkw1536** [comment]
In additon to this, I have also had problems with the sidebar when I resised the window and the sidebar was open.

**Comment by LiftnLearn** [comment]
It occurs when you hover over the sidebar at the height of any create/edit box.
