### ISSUE TITLE
Handle tooltip of multiple annotations on one element better

### ISSUE THREAD

**Issue by tkw1536** [KWARC/KAT#28]

**Comment by tkw1536** [comment]
see https://github.com/KWARC/KAT/blob/dev/src/KAT/storage/annotation.js#L422-L510

**Comment by LiftnLearn** [comment]
Is there any restriction on how I should do it or is it 'do whatever you think fits best'?

**Comment by tkw1536** [comment]
Nothing other than it should incorperate the tooltip of each of the individual annotations. I recently redid the syntax for \<display> element (#27) - the code for it is here: https://github.com/KWARC/KAT/blob/dev/src/KAT/storage/annotation.js#L554-L652

**Comment by LiftnLearn** [comment]
Done.
