### ISSUE TITLE
Tooltip not vanishing

### ISSUE THREAD

**Issue by LiftnLearn** [KWARC/KAT#31]
It seems like sometimes the tooltip doesn't disappear after you stop hovering over the annotation; although I'm not sure yet when exactly it appears nor if it's a KAT or JOBAD issue. Also I think there shouldn't be any tooltips shown under the sidebar when it's open.

**Comment by tkw1536** [comment]
It's probably a JOBAD issue.

**Comment by LiftnLearn** [comment]
Are you gonna do anything about it? Or should we switch to another library?

**Comment by tkw1536** [comment]
I will look into it next week and see what causes it.

**Comment by tkw1536** [comment]
Finally fixed the issue.
