### ISSUE TITLE
Fix math highlighting

### ISSUE THREAD

**Issue by LiftnLearn** [KWARC/KAT#44]
The function KAT.storage.gui.getRange(...) doesn't seem to include the math expressions.

**Comment by tkw1536** [comment]
It does, just normal css attributes do not work on it because they are
mathml.  Maybe we could wrap them but that would break xpaths.

**Comment by LiftnLearn** [comment]
The math expressions should now be highlighted as well, but for some of the other math expressions the color is removed for the reviewing... Is there any way to compute the values of rgba() within jQuery so I can use it on the MathML expressions?

**Comment by tkw1536** [comment]
Sounds good. But what do you mean compute the rgba? Do you mean merging two colors?

**Comment by LiftnLearn** [comment]
I want to take the color of the math expressions and compute the value that the rgba() CSS-function would give so it matches the color of the overlay-div. But MathML doesn't take css and I don't know how to compute the new color value in HEX since there seems to be no such function in javaScript. You could consider it merging two colors if you merge the color of the overlay and the color of the annotation.

**Comment by tkw1536** [comment]
Once you have an RBG(A) colors, you can easily merge two of them (just take the average of each value or something). To convert hex to rgb, see for example http://stackoverflow.com/a/5624139
Afterwards you can just set the color with something like ```$(...).css('color', 'rgba(0,0,0,0)')```.
