### ISSUE TITLE
Using library for SVG

### ISSUE THREAD

**Issue by LiftnLearn** [KWARC/KAT#53]
As it turns out, it is not that easy to combine SVG and jQuery(http://stackoverflow.com/questions/6793312/how-to-use-jquery-in-svg-scalable-vector-graphics#answer-6794343). Tom said though that I should try not to use any more libraries. Can we make an exception for this (there seem to be also some jQuery plugins) ? I can try to work around this somehow, but that would restrict the arrows for the references to a rather basic functionality...

**Comment by tkw1536** [comment]
@LiftnLearn  Sounds good. Before including it, please let me know which license it has so we can make sure its compatible.

**Comment by LiftnLearn** [comment]
Is this fine? : http://raphaeljs.com/
It's under the MIT license.

**Comment by tkw1536** [comment]
Sounds good.

**Comment by LiftnLearn** [comment]
Why do we concatenate the dot.js file to our source code and import the JOBAD libraries in the index.html?

**Comment by tkw1536** [comment]
JOBAD is a stand-alone library (complete with its own dependencies). It also has CSS components hence it makes little sense to append it to our source files. Furthermore KAT was meant to be usable as a JOBAD module at some point. 

dot.js on the other hand is relatively small so we concatenate it to our source files. It saves KAT users from having to include it manually.
