### ISSUE TITLE
Error for concept without fields

### ISSUE THREAD

**Issue by jfschaefer** [KWARC/KAT#57]
According to schema/kannspec.rnc (line 29), a concept can have an arbitrary number of fields, including none.
However, I get the following error for a kannspec with a concept that has no fields:
```.model.ParsingError: KAT.model.Concept: Invalid XML for concept 'Declarations.Variable' (Missing at least one declared <field>).```

**Comment by tkw1536** [comment]
Should be easy to fix, I will take a look tomorrow (for reference:  https://github.com/KWARC/KAT/blob/4e5a6dd2cf53f49de700fb9c93808b3582143b9d/src/KAT/model/Concept.js#L124-L136 )

**Comment by kohlhase** [comment]
there is still the possibility that allowing no fields is an error itself; does this sound useful?

**Comment by tkw1536** [comment]
IIRC the use case for this was to annotate something is a symbol (without
any further properties) and then being able to refer to it (Effectively
working around the fact that an annotation can only have one associated
text range )
@jschaefer is that correct?

**Comment by kohlhase** [comment]
yes, that sounds very sensible, so please fix it.
